SELECT APELLIDO_PATERNO
FROM PROFESOR
ORDER BY APELLIDO_PATERNO ASC;  --ASC ordena de A-Z y DESC para ordenar de Z-A

SELECT APELLIDO_PATERNO, APELLIDO_MATERNO
FROM PROFESOR
ORDER BY APELLIDO_PATERNO, APELLIDO_MATERNO;    --Por defecto se ordena con ASC


SELECT APELLIDO_PATERNO
FROM PROFESOR
ORDER BY APELLIDO_PATERNO ASC;

--DISTINCT (distingue dos datos repetidos y solo muestra uno), UNIQUE (es igual que DISTING) y ALL

SELECT DISTINCT APELLIDO_PATERNO
FROM PROFESOR
ORDER BY APELLIDO_PATERNO ASC;

COLUMN FECHA_FIN FORMAT A9;
COLUMN DUMMY FORMAT A12;
