--EJERCICIO 1
SELECT C.CLAVE_GRUPO, C.CUPO_MAXIMO, P.NOMBRE, H.DIA_SEMANA, H.HORA_INICIO, H.HORA_FIN
FROM
ASIGNATURA A INNER JOIN CURSO C ON A.ASIGNATURA_ID = C.ASIGNATURA_ID
INNER JOIN PROFESOR P ON P.PROFESOR_ID = C.PROFESOR_ID
INNER JOIN CURSO_HORARIO CH ON CH.CURSO_ID = C.CURSO_ID
INNER JOIN HORARIO H ON H.HORARIO_ID = CH.HORARIO_ID
INNER JOIN SEMESTRE S ON C.SEMESTRE_ID = S.SEMESTRE_ID
WHERE A.NOMBRE = 'CALCULO 2' AND S.ANIO = 2008 AND S.PERIODO = 1;


--EJERCICIO 2
SELECT A.NOMBRE, C.CURSO_ID, C.CLAVE_GRUPO
FROM
ASIGNATURA A INNER JOIN CURSO C ON C.ASIGNATURA_ID = A.ASIGNATURA_ID
INNER JOIN ESTUDIANTE_INSCRITO EI ON C.CURSO_ID = EI.CURSO_ID
WHERE EI.CALIFICACION IS NULL;


--EJERCICIO 3
SELECT *
FROM
PROFESOR P NATURAL JOIN CURSO C
WHERE P.APELLIDO_PATERNO = 'KRAUCE';
