/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prebeeditor;

import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {        //Lo que hice en el constructor es decirle al constructor que sea visivble todo
        initComponents();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        ingresarBtn = new javax.swing.JButton();
        passwordPf = new javax.swing.JPasswordField();
        usuarioTf = new javax.swing.JTextField();
        iconL = new javax.swing.JLabel();
        fondoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(ingresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        passwordPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPfActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(passwordPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 160, -1));

        usuarioTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTfActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(usuarioTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 160, 30));

        iconL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prebeeditor/man-icon.png"))); // NOI18N
        contenedorPrincipal.add(iconL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        fondoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prebeeditor/fondo.png"))); // NOI18N
        contenedorPrincipal.add(fondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 550, 511));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contenedorPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPfActionPerformed

    private void usuarioTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTfActionPerformed

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        // TODO add your handling code here:
        String usuario = usuarioTf.getText();       //Para leer el usuario
        char [] contrasena = passwordPf.getPassword();
        String pass = new String(contrasena);       //El constructor de String le paso un arreglo de char y me lo convierte a cadena
        
        if (usuario.equals("root") && pass.equals("toor")) {
            System.out.println("Sí funcionó PRRO!");
            JOptionPane.showMessageDialog(this, "Credenciales correctars para el loggin");      //this es paea hacer referencia la componente padre
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas");
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JLabel fondoL;
    private javax.swing.JLabel iconL;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JPasswordField passwordPf;
    private javax.swing.JTextField usuarioTf;
    // End of variables declaration//GEN-END:variables
}
